meta_product_name: "ember"
meta_title: "ember - Helps you remember the little things, while focusing on the big."
meta_description: "Helps you remember the little things, while focusing on the big."
meta_image: "homebackground.png" # should exist in `app/assets/images/`
