meta_product_name: "Ember"
meta_title: "Ember-Helps you do remember the little things, while focusing on the big."
meta_description: "Helps you do remember the little things, while focusing on the big."
meta_image: "homebackground.png" # should exist in `app/assets/images/`

